# Generated by Django 6.0.2 on 2026-02-22 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_birthday_image_alter_birthday_birthday_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthday',
            options={'verbose_name': 'День Рождение', 'verbose_name_plural': 'Дни Рождения'},
        ),
    ]
