# Generated by Django 6.0.2 on 2026-02-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0006_tag_birthday_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Метка-Тэг', 'verbose_name_plural': 'Метки-Тэги'},
        ),
    ]
